eTickets/Controllers/ActorsController.cs
using eTickets.Data.Services;
using eTickets.Data.ViewModels;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorsService _service;
        private readonly ILogger<ActorsController> logger;

        public ActorsController(IActorsService service , ILogger<ActorsController> logger)
        {
            _service = service;
            this.logger = logger;
        }

        #region Index
        public async Task<IActionResult> Index()
        {
            string loggerSignature = "ActorsController ==> Index : ";
            var allActors = await _service.GetAllAsync();
            logger.LogInformation($"{loggerSignature} get all actors from database successfully");
            return View(allActors);
        }
        #endregion


        #region create 

        /* Create new actor
         * go to form post create
         */
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        /* go to form post 
            * check the model if vaild from user 
            * if no return the same view with the model error 
            * if yes AddAsync the new actor
            */
        [HttpPost]
        public async Task<IActionResult> Create(Actor newActor)
        {
            string loggerSignature = "ActorsController ==> Create Post : ";
            if (!ModelState.IsValid)
            {
                return View(newActor);
            }
            logger.LogError($"{loggerSignature} is not valid model");
             await _service.AddAsync(newActor);
            logger.LogInformation($"{loggerSignature} is added successfully");
            return RedirectToAction("Index");
        }
        #endregion

        #region Details

        //Details
        public async Task<IActionResult> Details (int id)
        {
           var actor = await _service.GetByIdAsync(id);
            if(actor is null)
                return View("NotFound");
            
            return View(actor);
        }

        #endregion


        #region Edit

        /* 1* get the actor id to check if there is an actor with this id
         * if No return view Notfound
         * if yesreturn a view with form post to get the update 
         */
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var actor = await _service.GetByIdAsync(id);
            if (actor is null)
                return View("NotFound");
            return View(actor);
        }


        /* 2* get the id and the new actor parameters the changed from user 
         * the actor param is will use to return the same view if the model is not vaild 
         * if model vaild will go to UpdateAsync to update the actor 
         */
        [HttpPost]
        public async Task<IActionResult> Edit(Actor actor)
        {
            if (!ModelState.IsValid)
                return View(actor);
            await _service.UpdateAsync(actor);
            return RedirectToAction("Index");

        }

        #endregion

        #region Delete
        [HttpGet]
        public async Task<IActionResult> Delete (int id)
        {
            var actor = await _service.GetByIdAsync(id);
            if (actor is null)
                return View("NotFound");
            return View(actor);
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            /*check
             * if no return not found 
             * if yes will delte
             */
 
            await _service.DeleteAsync(id);
            return RedirectToAction("index");

        }
        #endregion 

    }
}

eTickets/Controllers/CinemasController.cs
using eTickets.Data.Services;
using eTickets.Data.ViewModels;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers
{
    public class CinemasController : Controller
    {
        private readonly ICinemasService _service;

        public CinemasController(ICinemasService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var allCinemas = await _service.GetAllAsync();
            return View(allCinemas);
        }

        #region Create

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create (Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }
            await _service.AddAsync(cinema);
            return RedirectToAction("Index");
        }

        #endregion

        #region Details
        public async Task<IActionResult> Details (int id)
        {
            var cinema = await _service.GetByIdAsync(id);
            if (cinema is null) return View("NotFound");
            return View(cinema);
        }
        #endregion

        #region Edit
        [HttpGet]
        public async Task<IActionResult> Edit (int id)
        {
            var cinema = await _service.GetByIdAsync(id);
            if (cinema is null) return View("NotFound");
            return View(cinema);
        }

        [HttpPost]
        public async Task<IActionResult> Edit (Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }
            await _service.UpdateAsync(cinema);
            return RedirectToAction("Index");
        }

        #endregion

        #region Delete

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var cinema = await _service.GetByIdAsync(id);
            if (cinema is null) return View("NotFound");
            return View(cinema);
        }

        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

eTickets/Controllers/MoviesController.cs
using eTickets.Data.Services;
using eTickets.Data.ViewModels;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMoviesService _service;

        public MoviesController(IMoviesService service)
        {
            _service = service;
        }


        #region Index
        public async Task<IActionResult> Index()
        {
            var allMovies = await _service.GetAllIncludeAsync(i=>i.Cinema);
            return View(allMovies);
        }
        #endregion

        public async Task<IActionResult> Filter(string searchString)
        {
            
                var allMovies = await _service.GetAllIncludeAsync(n => n.Cinema);

                if (string.IsNullOrEmpty(searchString))
                      return View("Index", allMovies);

            var filteredResult = allMovies.Where
                (n => n.Name.ToLower().Contains(searchString.ToLower()) ||
                n.Description.ToLower().Contains(searchString.ToLower()))
                .ToList();

                    return View("Index", filteredResult);

            
        }

        #region Details
        [HttpGet]
        public async Task<IActionResult> Details (int id)
        {
            var movieDetails = await _service.GetMovieByIdAsync(id);
            return View(movieDetails);
        }
        #endregion

        #region Create
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var movieDropdownsData = await _service.GetNewMovieDropValuesAsync();

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");


            return View();  
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewMovieVM newMovieVM)
        {
            if(!ModelState.IsValid)
            {
                var movieDropdownsData = await _service.GetNewMovieDropValuesAsync();

                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

                return View(newMovieVM);
            }


            await _service.AddNewMoiveAsync(newMovieVM);

            return RedirectToAction(nameof(Index));
            

        }
        #endregion

        #region Edit

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
           var movie = await _service.GetMovieByIdAsync(id);
            if(movie == null)
                return View("NotFound");
            var response = new NewMovieVM
            {
                Id = movie.Id,
                Name = movie.Name,
                ImageURL = movie.ImageURL,
                Price = movie.Price,
                Description = movie.Description,
                StartDate = movie.StartDate,
                EndDate = movie.EndDate,
                CinemaId = movie.CinemaId,
                ProducerId = movie.ProducerId,
                MovieCategory =movie.MovieCategory, 
                ActorsIds = movie.Actors_Movies.Select(i=>i.ActorId).ToList()
            };
            var movieDropdownsData = await _service.GetNewMovieDropValuesAsync();

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View(response);


        }

        [HttpPost]
        public async Task<IActionResult> Edit (NewMovieVM movie)
        {
            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _service.GetNewMovieDropValuesAsync();

                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

                return View(movie);
            }
            await _service.UpdateMovieAsync(movie);
            return RedirectToAction(nameof(Index)); 
        }

        #endregion
    }
}

eTickets/Controllers/ProducersController.cs
using eTickets.Data.Services;
using eTickets.Data.ViewModels;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers
{
    public class ProducersController : Controller
    {
        private readonly IPoroducersService _service;

        public ProducersController(IPoroducersService service )
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var allProducers = await _service.GetAllAsync(); 
            return View(allProducers);
        }

        #region Details
        public async Task<IActionResult> Details (int id)
        {
            var producer = await _service.GetByIdAsync(id);
            if (producer is null)
                return View("NotFound");  
            return View(producer);
        }
        #endregion

        #region Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();  
        }
        [HttpPost]
        public async Task<IActionResult> Create(Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }
            await _service.AddAsync(producer);
            return RedirectToAction("Index");
        }
        #endregion

        #region Edit

        public async Task<IActionResult> Edit(int id)
        {
            var producer = await _service.GetByIdAsync(id);
            if(producer is null)
            {
                return View("NotFound");
            }
            return View(producer);
        }

        [HttpPost]
        public async Task<IActionResult> Edit (Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }
           await _service.UpdateAsync(producer);
            return RedirectToAction("Index");
        }

        #endregion

        [HttpGet]
        public async Task<IActionResult> Delete (int id)
        {
            var producer = await _service.GetByIdAsync(id); 
            if( producer is null)
            {
                return View("NotFound");
            }
            return View(producer);
        }

        [HttpPost]
        [ActionName ("Delete")]
        public async Task<IActionResult> DeleteConfirmed (int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction("Index");   
        }
    }
}

eTickets/Views/Shared/NotFound.cshtml
<div class="row text-center">
    <div class="col-md-12 offset-0">
    <h1 class="text-info">We have reached the end of the internet </h1>
    <hr/>
    <a class="btn btn-outline-success" asp-controller="Movies" asp-action="Index">Home Page</a>
    </div>
</div>

eTickets/Views/Shared/_CreateItem.cshtml
@model string;

<div style="position:fixed; left:25px; bottom:25px;">
    <a asp-controller="@Model" asp-action="Create" class="btn btn-success"> 
        <i class="bi bi-plus-circle"></i> Add New</a>
</div>

eTickets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Movies" asp-action="Index">eTickets</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index"><i class="bi bi-film"></i> Movies</a>
                        </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="bi bi-gear"></i> Management
                                    </a>

                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index"><i class="bi bi-camera-reels"></i> Cinemas</a>
                                        <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i> Producers</a>
                                        <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-square"></i> Actors</a>
                                    </div>
                                </li>
                        
                    </ul>

                   <form class="form-inline my-2 my-lg-0 d-flex justify-content-center" asp-controller="Movies" asp-action="Filter" style="padding-right: 25px;">
                    <div class="d-flex align-items-center" style="margin-right: 10px;">
                     <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." aria-label="Recipient's username" aria-describedby="button-addon2">
                    </div>
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                   

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Ahmed Yasser - 2024 - eTickets
        </div>
    </footer>
   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>